springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    docExpansion: none
    defaultModelsExpandDepth: -1
spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:park}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  mail:
    host: ${MAIL_HOST:SMTP_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:MAIL_USERNAME}
    password: ${MAIL_PASSWORD:MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          from: ${MAIL_FROM:park@luizpaulino.com}
          auth: true
          starttls:
            enable: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
server:
  port: ${SERVER_PORT:9999}
