version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: park
    networks:
      - park
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --notify-keyspace-events KEx
    networks:
      - park
  park1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: park1
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider localhost:9999/actuator/health || exit 1"
      interval: 3s
      timeout: 5s
      retries: 10
    depends_on:
      - mongodb
      - redis
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: park
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 9999
      MAIL_HOST: SMTP_HOST
      MAIL_PORT: 587
      MAIL_USERNAME: MAIL_USERNAME
      MAIL_PASSWORD: MAIL_PASSWORD
      MAIL_FROM: park@luizpaulino.com
    networks:
      - park
  park2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: park2
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider localhost:9999/actuator/health || exit 1"
      interval: 3s
      timeout: 5s
      retries: 10
    depends_on:
      - mongodb
      - redis
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: park
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 9999
      MAIL_HOST: SMTP_HOST
      MAIL_PORT: 587
      MAIL_USERNAME: MAIL_USERNAME
      MAIL_PASSWORD: MAIL_PASSWORD
      MAIL_FROM: park@luizpaulino.com
    networks:
      - park
  nginx: # Load Balancer
    image: nginx:latest
    depends_on:
      park1:
        condition: service_healthy
      park2:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - park

networks:
  park:
    driver: bridge